apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/kurazuuuuuu/krz-tech-portfolio
    digest: sha256:bc847bc187489f7fb9f00091d5bd6f9904c4270544f0901f1ea2935a8886ee89
