apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/kurazuuuuuu/krz-tech-portfolio
  newTag: f4d047d9864c976edcf852a52409f77246df7b65
