apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/kurazuuuuuu/krz-tech-portfolio
  newTag: 95aed27dd832ed16bcbb4dbe2e483ae8c7395bcc
