apiVersion: v1
kind: Service
metadata:
  name: krz-tech-portfolio-lb
  namespace: argocd-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: krz-tech-portfolio
  type: LoadBalancer
  loadBalancerIP: 192.168.1.21