name: CI
on:
    push: 
        branches: [main]
    pull_request:
        branches: [main]

permissions:
  contents: read
  packages: write

jobs:
    build:
        runs-on: ci-krz-tech-portfolio
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Login to GitHub Container Registry
          run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
        - name: Build Docker image
          run: |
            docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
            docker build -t ghcr.io/${{ github.repository }}:latest .
            
        - name: Push Docker image
          run: |
            docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
            docker push ghcr.io/${{ github.repository }}:latest
